version: '3.7'
services:
  gmdb-users-svc:
    image: gmdb/users-svc
    ports:
      - 8081:8081
    depends_on:
      - gmdb-devdb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://gmdb-devdb/gmdb?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=gmdb_app
      - SPRING_DATASOURCE_PASSWORD=1234
  gmdb-devdb:
    image: gmdb/devdb
    environment:
      - MYSQL_ROOT_PASSWORD 123
      - MYSQL_DATABASE gmdb
      - MYSQL_USER gmdb_app
      - MYSQL_PASSWORD 1234

